# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 095b519cb1e7f9f0d63a6f73f0ccd784a2504595afac5fb96665897c46d8f1575db66ce376c8574c628fe5b2f680b80f7bc9b413bd4f9be6d09041cefddf58de

test:
  secret_key_base: 71a06e276485acab35ed7735a3cbd7f42e9ffe615b4a92820244de6dc4d5bc55d6de6595b6278dce0aa2c00ac0805dd0c188d50a400cf3477bf8840a52889abb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
